<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Carbon;

class PaymentSeeder2 extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();
        $today = Carbon::today();

        // Status final dihitung ulang via helper agar konsisten dgn tanggal seeding.
        $st = function (string $dueDate, ?string $paidAt) use ($today): string {
            if ($paidAt)
                return 'paid';
            return Carbon::parse($dueDate)->lt($today) ? 'overdue' : 'pending';
        };

        $rows = [
            // id 1 YAYASAN DIAN KENCANA INTI 1 Gd AC  [interval]
            [
                'contract_id' => 1,
                'amendment_id' => null,
                'period_number' => 1,
                'due_date' => '2025-03-01',
                'paid_at' => '2025-03-01',
                'amount_due' => 95000000,
                'amount_paid' => 95000000,
                'notes' => 'Per tahun – periode 1',
            ],
            [
                'contract_id' => 1,
                'amendment_id' => null,
                'period_number' => 2,
                'due_date' => '2026-03-01',
                'paid_at' => '2026-03-01',
                'amount_due' => 95000000,
                'amount_paid' => 95000000,
                'notes' => 'Per tahun – periode 2',
            ],
            [
                'contract_id' => 1,
                'amendment_id' => null,
                'period_number' => 3,
                'due_date' => '2027-03-01',
                'paid_at' => null,
                'amount_due' => 95000000,
                'amount_paid' => 0,
                'notes' => 'Per tahun – periode 3',
            ],
            [
                'contract_id' => 1,
                'amendment_id' => null,
                'period_number' => 4,
                'due_date' => '2028-03-01',
                'paid_at' => null,
                'amount_due' => 95000000,
                'amount_paid' => 0,
                'notes' => 'Per tahun – periode 4',
            ],
            [
                'contract_id' => 1,
                'amendment_id' => null,
                'period_number' => 5,
                'due_date' => '2029-03-01',
                'paid_at' => null,
                'amount_due' => 95000000,
                'amount_paid' => 0,
                'notes' => 'Per tahun – periode 5',
            ],
            // id 2 PT DAYAMITRA TELEKOMUNIKASI Tb  [upfront]
            [
                'contract_id' => 2,
                'amendment_id' => null,
                'period_number' => 0,
                'due_date' => '2023-01-02',
                'paid_at' => '2023-01-02',
                'amount_due' => 1000000000,
                'amount_paid' => 1000000000,
                'notes' => '100% dibayar dimuka',
            ],
            // id 3 PT. INTI BUMI PERKASA Lt2  [upfront]
            [
                'contract_id' => 3,
                'amendment_id' => null,
                'period_number' => 0,
                'due_date' => '2026-01-01',
                'paid_at' => '2026-01-01',
                'amount_due' => 88164000,
                'amount_paid' => 88164000,
                'notes' => '100% dibayar dimuka',
            ],
            // id 4 PT. BANK NEGARA INDONESIA  [upfront]
            [
                'contract_id' => 4,
                'amendment_id' => null,
                'period_number' => 0,
                'due_date' => '2024-07-02',
                'paid_at' => '2024-07-02',
                'amount_due' => 96000000,
                'amount_paid' => 96000000,
                'notes' => '100% dibayar dimuka',
            ],
            // id 5 PT Mega Akses Persada Subduct  [upfront]
            [
                'contract_id' => 5,
                'amendment_id' => null,
                'period_number' => 0,
                'due_date' => '2025-08-23',
                'paid_at' => '2025-08-23',
                'amount_due' => 9600000,
                'amount_paid' => 9600000,
                'notes' => '100% dibayar dimuka',
            ],
            // id 6 PT CITRA INDUSTRI KERETA API  [upfront]
            [
                'contract_id' => 6,
                'amendment_id' => null,
                'period_number' => 0,
                'due_date' => '2026-03-01',
                'paid_at' => '2026-03-01',
                'amount_due' => 82620000,
                'amount_paid' => 82620000,
                'notes' => '100% dibayar dimuka',
            ],
            // id 7 INTIVENUE  [interval]
            [
                'contract_id' => 7,
                'amendment_id' => null,
                'period_number' => 1,
                'due_date' => '2025-09-01',
                'paid_at' => '2025-09-01',
                'amount_due' => 22500000,
                'amount_paid' => 22500000,
                'notes' => 'Per bulan – periode 1',
            ],
            [
                'contract_id' => 7,
                'amendment_id' => null,
                'period_number' => 2,
                'due_date' => '2025-10-01',
                'paid_at' => '2025-10-01',
                'amount_due' => 22500000,
                'amount_paid' => 22500000,
                'notes' => 'Per bulan – periode 2',
            ],
            [
                'contract_id' => 7,
                'amendment_id' => null,
                'period_number' => 3,
                'due_date' => '2025-11-01',
                'paid_at' => '2025-11-01',
                'amount_due' => 22500000,
                'amount_paid' => 22500000,
                'notes' => 'Per bulan – periode 3',
            ],
            [
                'contract_id' => 7,
                'amendment_id' => null,
                'period_number' => 4,
                'due_date' => '2025-12-01',
                'paid_at' => '2025-12-01',
                'amount_due' => 22500000,
                'amount_paid' => 22500000,
                'notes' => 'Per bulan – periode 4',
            ],
            [
                'contract_id' => 7,
                'amendment_id' => null,
                'period_number' => 5,
                'due_date' => '2026-01-01',
                'paid_at' => '2026-01-01',
                'amount_due' => 22500000,
                'amount_paid' => 22500000,
                'notes' => 'Per bulan – periode 5',
            ],
            [
                'contract_id' => 7,
                'amendment_id' => null,
                'period_number' => 6,
                'due_date' => '2026-02-01',
                'paid_at' => '2026-02-01',
                'amount_due' => 22500000,
                'amount_paid' => 22500000,
                'notes' => 'Per bulan – periode 6',
            ],
            [
                'contract_id' => 7,
                'amendment_id' => null,
                'period_number' => 7,
                'due_date' => '2026-03-01',
                'paid_at' => '2026-03-01',
                'amount_due' => 22500000,
                'amount_paid' => 22500000,
                'notes' => 'Per bulan – periode 7',
            ],
            [
                'contract_id' => 7,
                'amendment_id' => null,
                'period_number' => 8,
                'due_date' => '2026-04-01',
                'paid_at' => '2026-04-01',
                'amount_due' => 22500000,
                'amount_paid' => 22500000,
                'notes' => 'Per bulan – periode 8',
            ],
            [
                'contract_id' => 7,
                'amendment_id' => null,
                'period_number' => 9,
                'due_date' => '2026-05-01',
                'paid_at' => '2026-05-01',
                'amount_due' => 22500000,
                'amount_paid' => 22500000,
                'notes' => 'Per bulan – periode 9',
            ],
            [
                'contract_id' => 7,
                'amendment_id' => null,
                'period_number' => 10,
                'due_date' => '2026-06-01',
                'paid_at' => '2026-06-01',
                'amount_due' => 22500000,
                'amount_paid' => 22500000,
                'notes' => 'Per bulan – periode 10',
            ],
            [
                'contract_id' => 7,
                'amendment_id' => null,
                'period_number' => 11,
                'due_date' => '2026-07-01',
                'paid_at' => null,
                'amount_due' => 22500000,
                'amount_paid' => 0,
                'notes' => 'Per bulan – periode 11',
            ],
            [
                'contract_id' => 7,
                'amendment_id' => null,
                'period_number' => 12,
                'due_date' => '2026-08-01',
                'paid_at' => null,
                'amount_due' => 22500000,
                'amount_paid' => 0,
                'notes' => 'Per bulan – periode 12',
            ],
            // id 8 CV. CIPTA KREASINDO TEKNIKA  [upfront]
            [
                'contract_id' => 8,
                'amendment_id' => null,
                'period_number' => 0,
                'due_date' => '2026-03-01',
                'paid_at' => '2026-03-01',
                'amount_due' => 25830000,
                'amount_paid' => 25830000,
                'notes' => '100% dibayar dimuka',
            ],
            // id 9 PT. WIDYA BHAKTI INTI (WBI) Gd AA Lab  [upfront]
            [
                'contract_id' => 9,
                'amendment_id' => null,
                'period_number' => 0,
                'due_date' => '2021-12-01',
                'paid_at' => '2021-12-01',
                'amount_due' => 262400000,
                'amount_paid' => 262400000,
                'notes' => '100% dibayar dimuka',
            ],
            // id 10 PT. BANK MANDIRI, TBK  [upfront]
            [
                'contract_id' => 10,
                'amendment_id' => null,
                'period_number' => 0,
                'due_date' => '2025-12-13',
                'paid_at' => '2025-12-13',
                'amount_due' => 48000000,
                'amount_paid' => 48000000,
                'notes' => '100% dibayar dimuka',
            ],
            // id 11 PT. BANK CIMB NIAGA TBK  [upfront]
            [
                'contract_id' => 11,
                'amendment_id' => null,
                'period_number' => 0,
                'due_date' => '2023-12-30',
                'paid_at' => '2023-12-30',
                'amount_due' => 148500000,
                'amount_paid' => 148500000,
                'notes' => '100% dibayar dimuka',
            ],
            // id 13 Kepolisian Negara RI Daerah Jawa Barat  [upfront]
            [
                'contract_id' => 13,
                'amendment_id' => null,
                'period_number' => 0,
                'due_date' => '2026-01-01',
                'paid_at' => '2026-01-01',
                'amount_due' => 67567568,
                'amount_paid' => 67567568,
                'notes' => '100% dibayar dimuka',
            ],
            // id 14 PT. MITRA GRAHA INTI UTAMA (MGIU)  [upfront]
            [
                'contract_id' => 14,
                'amendment_id' => null,
                'period_number' => 0,
                'due_date' => '2026-01-01',
                'paid_at' => '2026-01-01',
                'amount_due' => 47848320,
                'amount_paid' => 47848320,
                'notes' => '100% dibayar dimuka',
            ],
            // id 15 PT MARLIP — tanpa jadwal (KSU revenue sharing — nilai variabel)
            // id 16 PT. WIDYA BHAKTI INTI (WBI) Gd D Apotik  [upfront]
            [
                'contract_id' => 16,
                'amendment_id' => null,
                'period_number' => 0,
                'due_date' => '2026-01-01',
                'paid_at' => '2026-01-01',
                'amount_due' => 30801600,
                'amount_paid' => 30801600,
                'notes' => '100% dibayar dimuka',
            ],
            // id 17 PT. INTI KONTEN INDONESIA  [interval]
            [
                'contract_id' => 17,
                'amendment_id' => null,
                'period_number' => 1,
                'due_date' => '2025-02-03',
                'paid_at' => '2025-02-03',
                'amount_due' => 264492000,
                'amount_paid' => 264492000,
                'notes' => 'Per tahun – periode 1',
            ],
            [
                'contract_id' => 17,
                'amendment_id' => null,
                'period_number' => 2,
                'due_date' => '2026-02-03',
                'paid_at' => '2026-02-03',
                'amount_due' => 264492000,
                'amount_paid' => 264492000,
                'notes' => 'Per tahun – periode 2',
            ],
            // id 18 JADDASOLUTION  [upfront]
            [
                'contract_id' => 18,
                'amendment_id' => null,
                'period_number' => 0,
                'due_date' => '2025-08-01',
                'paid_at' => '2025-08-01',
                'amount_due' => 15120000,
                'amount_paid' => 15120000,
                'notes' => '100% dibayar dimuka',
            ],
            // id 19 Elfia Minisoccer — tanpa jadwal (KSU revenue sharing — nilai variabel)
            // id 21 PT EPID MENARA ASSETCO  [upfront]
            [
                'contract_id' => 21,
                'amendment_id' => null,
                'period_number' => 0,
                'due_date' => '2023-06-05',
                'paid_at' => '2023-06-05',
                'amount_due' => 115133200,
                'amount_paid' => 115133200,
                'notes' => '100% dibayar dimuka',
            ],
            // id 23 PT. WIDYA BHAKTI INTI (WBI) Gd D Poli  [upfront]
            [
                'contract_id' => 23,
                'amendment_id' => null,
                'period_number' => 0,
                'due_date' => '2023-01-01',
                'paid_at' => '2023-01-01',
                'amount_due' => 787158000,
                'amount_paid' => 787158000,
                'notes' => '100% dibayar dimuka',
            ],
            // id 24 Parkir Palasari — tanpa jadwal (KSU revenue sharing — nilai variabel)
            // id 25 Parkir Toha 77 — tanpa jadwal (KSU revenue sharing — nilai variabel)
            // id 26 PT. BANK OCBC NISP,Tbk  [upfront]
            [
                'contract_id' => 26,
                'amendment_id' => null,
                'period_number' => 0,
                'due_date' => '2025-12-31',
                'paid_at' => '2025-12-31',
                'amount_due' => 151200000,
                'amount_paid' => 151200000,
                'notes' => '100% dibayar dimuka',
            ],
            // id 27 PT Navitas Educational Service  [interval]
            [
                'contract_id' => 27,
                'amendment_id' => null,
                'period_number' => 1,
                'due_date' => '2024-09-01',
                'paid_at' => '2024-09-01',
                'amount_due' => 1301410860,
                'amount_paid' => 1301410860,
                'notes' => 'Per 3 bulan – periode 1',
            ],
            [
                'contract_id' => 27,
                'amendment_id' => null,
                'period_number' => 2,
                'due_date' => '2024-12-01',
                'paid_at' => '2024-12-01',
                'amount_due' => 1301410860,
                'amount_paid' => 1301410860,
                'notes' => 'Per 3 bulan – periode 2',
            ],
            [
                'contract_id' => 27,
                'amendment_id' => null,
                'period_number' => 3,
                'due_date' => '2025-03-01',
                'paid_at' => '2025-03-01',
                'amount_due' => 1301410860,
                'amount_paid' => 1301410860,
                'notes' => 'Per 3 bulan – periode 3',
            ],
            [
                'contract_id' => 27,
                'amendment_id' => null,
                'period_number' => 4,
                'due_date' => '2025-06-01',
                'paid_at' => '2025-06-01',
                'amount_due' => 1301410860,
                'amount_paid' => 1301410860,
                'notes' => 'Per 3 bulan – periode 4',
            ],
            [
                'contract_id' => 27,
                'amendment_id' => null,
                'period_number' => 5,
                'due_date' => '2025-09-01',
                'paid_at' => '2025-09-01',
                'amount_due' => 1301410860,
                'amount_paid' => 1301410860,
                'notes' => 'Per 3 bulan – periode 5',
            ],
            [
                'contract_id' => 27,
                'amendment_id' => null,
                'period_number' => 6,
                'due_date' => '2025-12-01',
                'paid_at' => '2025-12-01',
                'amount_due' => 1301410860,
                'amount_paid' => 1301410860,
                'notes' => 'Per 3 bulan – periode 6',
            ],
            [
                'contract_id' => 27,
                'amendment_id' => null,
                'period_number' => 7,
                'due_date' => '2026-03-01',
                'paid_at' => '2026-03-01',
                'amount_due' => 1301410860,
                'amount_paid' => 1301410860,
                'notes' => 'Per 3 bulan – periode 7',
            ],
            [
                'contract_id' => 27,
                'amendment_id' => null,
                'period_number' => 8,
                'due_date' => '2026-06-01',
                'paid_at' => '2026-06-01',
                'amount_due' => 1301410860,
                'amount_paid' => 1301410860,
                'notes' => 'Per 3 bulan – periode 8',
            ],
            [
                'contract_id' => 27,
                'amendment_id' => null,
                'period_number' => 9,
                'due_date' => '2026-09-01',
                'paid_at' => null,
                'amount_due' => 1301410860,
                'amount_paid' => 0,
                'notes' => 'Per 3 bulan – periode 9',
            ],
            [
                'contract_id' => 27,
                'amendment_id' => null,
                'period_number' => 10,
                'due_date' => '2026-12-01',
                'paid_at' => null,
                'amount_due' => 1301410860,
                'amount_paid' => 0,
                'notes' => 'Per 3 bulan – periode 10',
            ],
            [
                'contract_id' => 27,
                'amendment_id' => null,
                'period_number' => 11,
                'due_date' => '2027-03-01',
                'paid_at' => null,
                'amount_due' => 1301410860,
                'amount_paid' => 0,
                'notes' => 'Per 3 bulan – periode 11',
            ],
            [
                'contract_id' => 27,
                'amendment_id' => null,
                'period_number' => 12,
                'due_date' => '2027-06-01',
                'paid_at' => null,
                'amount_due' => 1301410860,
                'amount_paid' => 0,
                'notes' => 'Per 3 bulan – periode 12',
            ],
            [
                'contract_id' => 27,
                'amendment_id' => null,
                'period_number' => 13,
                'due_date' => '2027-09-01',
                'paid_at' => null,
                'amount_due' => 1301410860,
                'amount_paid' => 0,
                'notes' => 'Per 3 bulan – periode 13',
            ],
            [
                'contract_id' => 27,
                'amendment_id' => null,
                'period_number' => 14,
                'due_date' => '2027-12-01',
                'paid_at' => null,
                'amount_due' => 1301410860,
                'amount_paid' => 0,
                'notes' => 'Per 3 bulan – periode 14',
            ],
            [
                'contract_id' => 27,
                'amendment_id' => null,
                'period_number' => 15,
                'due_date' => '2028-03-01',
                'paid_at' => null,
                'amount_due' => 1301410860,
                'amount_paid' => 0,
                'notes' => 'Per 3 bulan – periode 15',
            ],
            [
                'contract_id' => 27,
                'amendment_id' => null,
                'period_number' => 16,
                'due_date' => '2028-06-01',
                'paid_at' => null,
                'amount_due' => 1301410860,
                'amount_paid' => 0,
                'notes' => 'Per 3 bulan – periode 16',
            ],
            [
                'contract_id' => 27,
                'amendment_id' => null,
                'period_number' => 17,
                'due_date' => '2028-09-01',
                'paid_at' => null,
                'amount_due' => 1301410860,
                'amount_paid' => 0,
                'notes' => 'Per 3 bulan – periode 17',
            ],
            [
                'contract_id' => 27,
                'amendment_id' => null,
                'period_number' => 18,
                'due_date' => '2028-12-01',
                'paid_at' => null,
                'amount_due' => 1301410860,
                'amount_paid' => 0,
                'notes' => 'Per 3 bulan – periode 18',
            ],
            [
                'contract_id' => 27,
                'amendment_id' => null,
                'period_number' => 19,
                'due_date' => '2029-03-01',
                'paid_at' => null,
                'amount_due' => 1301410860,
                'amount_paid' => 0,
                'notes' => 'Per 3 bulan – periode 19',
            ],
            [
                'contract_id' => 27,
                'amendment_id' => null,
                'period_number' => 20,
                'due_date' => '2029-06-01',
                'paid_at' => null,
                'amount_due' => 1301410860,
                'amount_paid' => 0,
                'notes' => 'Per 3 bulan – periode 20',
            ],
            // id 28 YAYASAN DIAN KENCANA INTI 2 Gd AD  [interval]
            [
                'contract_id' => 28,
                'amendment_id' => null,
                'period_number' => 1,
                'due_date' => '2024-11-01',
                'paid_at' => '2024-11-01',
                'amount_due' => 200000000,
                'amount_paid' => 200000000,
                'notes' => 'Per tahun – periode 1',
            ],
            [
                'contract_id' => 28,
                'amendment_id' => null,
                'period_number' => 2,
                'due_date' => '2025-11-01',
                'paid_at' => '2025-11-01',
                'amount_due' => 200000000,
                'amount_paid' => 200000000,
                'notes' => 'Per tahun – periode 2',
            ],
            [
                'contract_id' => 28,
                'amendment_id' => null,
                'period_number' => 3,
                'due_date' => '2026-11-01',
                'paid_at' => null,
                'amount_due' => 200000000,
                'amount_paid' => 0,
                'notes' => 'Per tahun – periode 3',
            ],
            [
                'contract_id' => 28,
                'amendment_id' => null,
                'period_number' => 4,
                'due_date' => '2027-11-01',
                'paid_at' => null,
                'amount_due' => 200000000,
                'amount_paid' => 0,
                'notes' => 'Per tahun – periode 4',
            ],
            [
                'contract_id' => 28,
                'amendment_id' => null,
                'period_number' => 5,
                'due_date' => '2028-11-01',
                'paid_at' => null,
                'amount_due' => 200000000,
                'amount_paid' => 0,
                'notes' => 'Per tahun – periode 5',
            ],
        ];

        foreach ($rows as $row) {
            $row['payment_status'] = $st($row['due_date'], $row['paid_at']);
            DB::table('payments')->insert(array_merge($row, [
                'created_at' => $now,
                'updated_at' => $now,
            ]));
        }
    }
}
