<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Carbon;

class TestContractSeeder2 extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();

        // 'id' diisi eksplisit agar konsisten dgn referensi FK di ContractAsset & PaymentSeeder.
        // (kontrak #12 Koperasi, #20 Target Media LED, #22 DMANTEN sengaja dilewati.)
        $contracts = [
            // id 1: YAYASAN DIAN KENCANA INTI 1 Gd AC  (id_tenant bisnis: 40194)
            [
                'id' => 1,
                'tenant_id' => 22,
                'contract_type' => 'sewa',
                'no_bak' => '36/HK.03/030300/2025',
                'date_bak' => '2025-03-04',
                'file_bak' => null,
                'no_pks' => '38/HK.03/030300/2025',
                'date_pks' => '2025-03-10',
                'file_pks' => null,
                'start_date' => '2025-03-01',
                'end_date' => '2030-02-28',
                'total_rental_value' => 475000000,
                'security_deposit' => null,
                'sharing_type' => null,
                'company_share_pct' => null,
                'tenant_share_pct' => null,
                'payment_type' => 'interval',
                'payment_start_date' => '2025-03-01',
                'payment_interval_value' => 1,
                'payment_interval_unit' => 'year',
                'status' => 'active',
                'pihak_pertama' => 'PT INTI (Persero)',
                'pihak_kedua' => 'YAYASAN DIAN KENCANA INTI 1 Gd AC',
                'renewal_notes' => 'Per tahun',
            ],
            // id 2: PT DAYAMITRA TELEKOMUNIKASI Tb  (id_tenant bisnis: 40215)
            [
                'id' => 2,
                'tenant_id' => 15,
                'contract_type' => 'sewa',
                'no_bak' => '013/PL.01/030300/2023',
                'date_bak' => '2023-03-13',
                'file_bak' => null,
                'no_pks' => '53/H3.03/030300/2023',
                'date_pks' => '2023-03-13',
                'file_pks' => null,
                'start_date' => '2023-01-02',
                'end_date' => '2033-01-01',
                'total_rental_value' => 1000000000,
                'security_deposit' => null,
                'sharing_type' => null,
                'company_share_pct' => null,
                'tenant_share_pct' => null,
                'payment_type' => 'upfront',
                'payment_start_date' => '2023-01-02',
                'payment_interval_value' => 1,
                'payment_interval_unit' => 'year',
                'status' => 'active',
                'pihak_pertama' => 'PT INTI (Persero)',
                'pihak_kedua' => 'PT DAYAMITRA TELEKOMUNIKASI Tb',
                'renewal_notes' => '100% dibayar dimuka',
            ],
            // id 3: PT. INTI BUMI PERKASA Lt2  (id_tenant bisnis: 40046)
            [
                'id' => 3,
                'tenant_id' => 12,
                'contract_type' => 'sewa',
                'no_bak' => '6/HK.03/030301/2026',
                'date_bak' => '2026-01-13',
                'file_bak' => null,
                'no_pks' => null,
                'date_pks' => null,
                'file_pks' => null,
                'start_date' => '2026-01-01',
                'end_date' => '2026-06-30',
                'total_rental_value' => 88164000,
                'security_deposit' => null,
                'sharing_type' => null,
                'company_share_pct' => null,
                'tenant_share_pct' => null,
                'payment_type' => 'upfront',
                'payment_start_date' => '2026-01-01',
                'payment_interval_value' => 1,
                'payment_interval_unit' => 'year',
                'status' => 'active',
                'pihak_pertama' => 'PT INTI (Persero)',
                'pihak_kedua' => 'PT. INTI BUMI PERKASA Lt2',
                'renewal_notes' => 'Balancing || Skema BALANCING — disederhanakan jadi 1 pembayaran upfront, perlu rekonsiliasi manual',
            ],
            // id 4: PT. BANK NEGARA INDONESIA  (id_tenant bisnis: 40033)
            [
                'id' => 4,
                'tenant_id' => 27,
                'contract_type' => 'sewa',
                'no_bak' => null,
                'date_bak' => null,
                'file_bak' => null,
                'no_pks' => '97/HK.03/030302/2024',
                'date_pks' => '2022-07-11',
                'file_pks' => null,
                'start_date' => '2024-07-02',
                'end_date' => '2026-07-01',
                'total_rental_value' => 96000000,
                'security_deposit' => null,
                'sharing_type' => null,
                'company_share_pct' => null,
                'tenant_share_pct' => null,
                'payment_type' => 'upfront',
                'payment_start_date' => '2024-07-02',
                'payment_interval_value' => 1,
                'payment_interval_unit' => 'year',
                'status' => 'active',
                'pihak_pertama' => 'PT INTI (Persero)',
                'pihak_kedua' => 'PT. BANK NEGARA INDONESIA',
                'renewal_notes' => '100% dibayar dimuka',
            ],
            // id 5: PT Mega Akses Persada Subduct  (id_tenant bisnis: 40243)
            [
                'id' => 5,
                'tenant_id' => 17,
                'contract_type' => 'sewa',
                'no_bak' => '169/HK.03/030301/2025',
                'date_bak' => '2025-10-02',
                'file_bak' => null,
                'no_pks' => null,
                'date_pks' => null,
                'file_pks' => null,
                'start_date' => '2025-08-23',
                'end_date' => '2026-08-22',
                'total_rental_value' => 9600000,
                'security_deposit' => null,
                'sharing_type' => null,
                'company_share_pct' => null,
                'tenant_share_pct' => null,
                'payment_type' => 'upfront',
                'payment_start_date' => '2025-08-23',
                'payment_interval_value' => 1,
                'payment_interval_unit' => 'year',
                'status' => 'active',
                'pihak_pertama' => 'PT INTI (Persero)',
                'pihak_kedua' => 'PT Mega Akses Persada Subduct',
                'renewal_notes' => '100% dibayar dimuka',
            ],
            // id 6: PT CITRA INDUSTRI KERETA API  (id_tenant bisnis: 40175)
            [
                'id' => 6,
                'tenant_id' => 2,
                'contract_type' => 'sewa',
                'no_bak' => '39/HK.03/030301/2026',
                'date_bak' => '2026-02-13',
                'file_bak' => null,
                'no_pks' => null,
                'date_pks' => null,
                'file_pks' => null,
                'start_date' => '2026-03-01',
                'end_date' => '2026-08-31',
                'total_rental_value' => 82620000,
                'security_deposit' => null,
                'sharing_type' => null,
                'company_share_pct' => null,
                'tenant_share_pct' => null,
                'payment_type' => 'upfront',
                'payment_start_date' => '2026-03-01',
                'payment_interval_value' => 1,
                'payment_interval_unit' => 'year',
                'status' => 'active',
                'pihak_pertama' => 'PT INTI (Persero)',
                'pihak_kedua' => 'PT CITRA INDUSTRI KERETA API',
                'renewal_notes' => '100% dibayar dimuka',
            ],
            // id 7: INTIVENUE  (id_tenant bisnis: 40159)
            [
                'id' => 7,
                'tenant_id' => 41,
                'contract_type' => 'sewa',
                'no_bak' => '135/HK.03/030300/2025',
                'date_bak' => '2025-08-11',
                'file_bak' => null,
                'no_pks' => '143/HK.03/030300/2025',
                'date_pks' => '2025-08-20',
                'file_pks' => null,
                'start_date' => '2025-09-01',
                'end_date' => '2026-08-31',
                'total_rental_value' => 270000000,
                'security_deposit' => null,
                'sharing_type' => null,
                'company_share_pct' => null,
                'tenant_share_pct' => null,
                'payment_type' => 'interval',
                'payment_start_date' => '2025-09-01',
                'payment_interval_value' => 1,
                'payment_interval_unit' => 'month',
                'status' => 'active',
                'pihak_pertama' => 'PT INTI (Persero)',
                'pihak_kedua' => 'INTIVENUE',
                'renewal_notes' => 'Per Bulan || Nilai berbasis THRESHOLD (minimum guarantee) — diklasifikasikan sewa sementara, verifikasi apakah seharusnya KSU',
            ],
            // id 8: CV. CIPTA KREASINDO TEKNIKA  (id_tenant bisnis: 40009)
            [
                'id' => 8,
                'tenant_id' => 32,
                'contract_type' => 'sewa',
                'no_bak' => '37/HK.03/030301/2026',
                'date_bak' => '2026-02-13',
                'file_bak' => null,
                'no_pks' => null,
                'date_pks' => null,
                'file_pks' => null,
                'start_date' => '2026-03-01',
                'end_date' => '2026-08-31',
                'total_rental_value' => 25830000,
                'security_deposit' => null,
                'sharing_type' => null,
                'company_share_pct' => null,
                'tenant_share_pct' => null,
                'payment_type' => 'upfront',
                'payment_start_date' => '2026-03-01',
                'payment_interval_value' => 1,
                'payment_interval_unit' => 'year',
                'status' => 'active',
                'pihak_pertama' => 'PT INTI (Persero)',
                'pihak_kedua' => 'CV. CIPTA KREASINDO TEKNIKA',
                'renewal_notes' => '100% dibayar dimuka',
            ],
            // id 9: PT. WIDYA BHAKTI INTI (WBI) Gd AA Lab  (id_tenant bisnis: 40060)
            [
                'id' => 9,
                'tenant_id' => 23,
                'contract_type' => 'sewa',
                'no_bak' => '209/HK.03/020804/2021',
                'date_bak' => '2021-11-16',
                'file_bak' => null,
                'no_pks' => '16/HK.03/020804/2022',
                'date_pks' => '2022-02-03',
                'file_pks' => null,
                'start_date' => '2021-12-01',
                'end_date' => '2026-11-30',
                'total_rental_value' => 262400000,
                'security_deposit' => null,
                'sharing_type' => null,
                'company_share_pct' => null,
                'tenant_share_pct' => null,
                'payment_type' => 'upfront',
                'payment_start_date' => '2021-12-01',
                'payment_interval_value' => 1,
                'payment_interval_unit' => 'year',
                'status' => 'active',
                'pihak_pertama' => 'PT INTI (Persero)',
                'pihak_kedua' => 'PT. WIDYA BHAKTI INTI (WBI) Gd AA Lab',
                'renewal_notes' => 'Balancing || Skema BALANCING — disederhanakan jadi 1 pembayaran upfront, perlu rekonsiliasi manual',
            ],
            // id 10: PT. BANK MANDIRI, TBK  (id_tenant bisnis: 40134)
            [
                'id' => 10,
                'tenant_id' => 29,
                'contract_type' => 'sewa',
                'no_bak' => null,
                'date_bak' => null,
                'file_bak' => null,
                'no_pks' => '219/HK.03/030302/2025',
                'date_pks' => '2025-12-22',
                'file_pks' => null,
                'start_date' => '2025-12-13',
                'end_date' => '2026-12-12',
                'total_rental_value' => 48000000,
                'security_deposit' => null,
                'sharing_type' => null,
                'company_share_pct' => null,
                'tenant_share_pct' => null,
                'payment_type' => 'upfront',
                'payment_start_date' => '2025-12-13',
                'payment_interval_value' => 1,
                'payment_interval_unit' => 'year',
                'status' => 'active',
                'pihak_pertama' => 'PT INTI (Persero)',
                'pihak_kedua' => 'PT. BANK MANDIRI, TBK',
                'renewal_notes' => '100% dibayar dimuka',
            ],
            // id 11: PT. BANK CIMB NIAGA TBK  (id_tenant bisnis: 40083)
            [
                'id' => 11,
                'tenant_id' => 26,
                'contract_type' => 'sewa',
                'no_bak' => null,
                'date_bak' => null,
                'file_bak' => null,
                'no_pks' => '13/HK.03/030302/2024',
                'date_pks' => '2024-01-31',
                'file_pks' => null,
                'start_date' => '2023-12-30',
                'end_date' => '2026-12-29',
                'total_rental_value' => 148500000,
                'security_deposit' => null,
                'sharing_type' => null,
                'company_share_pct' => null,
                'tenant_share_pct' => null,
                'payment_type' => 'upfront',
                'payment_start_date' => '2023-12-30',
                'payment_interval_value' => 1,
                'payment_interval_unit' => 'year',
                'status' => 'active',
                'pihak_pertama' => 'PT INTI (Persero)',
                'pihak_kedua' => 'PT. BANK CIMB NIAGA TBK',
                'renewal_notes' => '100% dibayar dimuka',
            ],
            // id 13: Kepolisian Negara RI Daerah Jawa Barat  (id_tenant bisnis: 40232)
            [
                'id' => 13,
                'tenant_id' => 1,
                'contract_type' => 'sewa',
                'no_bak' => '222/HK.03/030300/2025',
                'date_bak' => '2025-12-29',
                'file_bak' => null,
                'no_pks' => null,
                'date_pks' => null,
                'file_pks' => null,
                'start_date' => '2026-01-01',
                'end_date' => '2026-12-31',
                'total_rental_value' => 67567568,
                'security_deposit' => null,
                'sharing_type' => null,
                'company_share_pct' => null,
                'tenant_share_pct' => null,
                'payment_type' => 'upfront',
                'payment_start_date' => '2026-01-01',
                'payment_interval_value' => 1,
                'payment_interval_unit' => 'year',
                'status' => 'active',
                'pihak_pertama' => 'PT INTI (Persero)',
                'pihak_kedua' => 'Kepolisian Negara RI Daerah Jawa Barat',
                'renewal_notes' => '100% dibayar dimuka',
            ],
            // id 14: PT. MITRA GRAHA INTI UTAMA (MGIU)  (id_tenant bisnis: 40051)
            [
                'id' => 14,
                'tenant_id' => 11,
                'contract_type' => 'sewa',
                'no_bak' => '10/HK.03/030301/2026',
                'date_bak' => '2026-01-20',
                'file_bak' => null,
                'no_pks' => null,
                'date_pks' => null,
                'file_pks' => null,
                'start_date' => '2026-01-01',
                'end_date' => '2026-12-31',
                'total_rental_value' => 47848320,
                'security_deposit' => null,
                'sharing_type' => null,
                'company_share_pct' => null,
                'tenant_share_pct' => null,
                'payment_type' => 'upfront',
                'payment_start_date' => '2026-01-01',
                'payment_interval_value' => 1,
                'payment_interval_unit' => 'year',
                'status' => 'active',
                'pihak_pertama' => 'PT INTI (Persero)',
                'pihak_kedua' => 'PT. MITRA GRAHA INTI UTAMA (MGIU)',
                'renewal_notes' => '100% dibayar dimuka',
            ],
            // id 15: PT MARLIP  (id_tenant bisnis: None)
            [
                'id' => 15,
                'tenant_id' => 48,
                'contract_type' => 'ksu',
                'no_bak' => '218/HK.03/030301/2025',
                'date_bak' => '2026-12-08',
                'file_bak' => null,
                'no_pks' => null,
                'date_pks' => null,
                'file_pks' => null,
                'start_date' => '2025-12-01',
                'end_date' => '2026-12-31',
                'total_rental_value' => null,
                'security_deposit' => null,
                'sharing_type' => 'revenue_sharing',
                'company_share_pct' => 1,
                'tenant_share_pct' => 99,
                'payment_type' => 'upfront',
                'payment_start_date' => '2025-12-01',
                'payment_interval_value' => 1,
                'payment_interval_unit' => 'year',
                'status' => 'active',
                'pihak_pertama' => 'PT INTI (Persero)',
                'pihak_kedua' => 'PT MARLIP',
                'renewal_notes' => 'Realisasi pendapatan revenue sharing periode Desember 2025 dengan porsi INTI 1 % sebesar Rp 3.300.000 dan sudah di setor ke PT INTI || KSU revenue_sharing; % porsi perusahaan diasumsikan 1.0% (verifikasi arah bagi hasil)',
            ],
            // id 16: PT. WIDYA BHAKTI INTI (WBI) Gd D Apotik  (id_tenant bisnis: 40060)
            [
                'id' => 16,
                'tenant_id' => 23,
                'contract_type' => 'sewa',
                'no_bak' => '24/HK.03/030301/2026',
                'date_bak' => '2026-02-02',
                'file_bak' => null,
                'no_pks' => null,
                'date_pks' => null,
                'file_pks' => null,
                'start_date' => '2026-01-01',
                'end_date' => '2026-12-31',
                'total_rental_value' => 30801600,
                'security_deposit' => null,
                'sharing_type' => null,
                'company_share_pct' => null,
                'tenant_share_pct' => null,
                'payment_type' => 'upfront',
                'payment_start_date' => '2026-01-01',
                'payment_interval_value' => 1,
                'payment_interval_unit' => 'year',
                'status' => 'active',
                'pihak_pertama' => 'PT INTI (Persero)',
                'pihak_kedua' => 'PT. WIDYA BHAKTI INTI (WBI) Gd D Apotik',
                'renewal_notes' => 'Balancing || Skema BALANCING — disederhanakan jadi 1 pembayaran upfront, perlu rekonsiliasi manual',
            ],
            // id 17: PT. INTI KONTEN INDONESIA  (id_tenant bisnis: 40047)
            [
                'id' => 17,
                'tenant_id' => 13,
                'contract_type' => 'sewa',
                'no_bak' => '10/HK.03/030302/2025',
                'date_bak' => '2025-02-10',
                'file_bak' => null,
                'no_pks' => null,
                'date_pks' => null,
                'file_pks' => null,
                'start_date' => '2025-02-03',
                'end_date' => '2027-02-02',
                'total_rental_value' => 528984000,
                'security_deposit' => null,
                'sharing_type' => null,
                'company_share_pct' => null,
                'tenant_share_pct' => null,
                'payment_type' => 'interval',
                'payment_start_date' => '2025-02-03',
                'payment_interval_value' => 1,
                'payment_interval_unit' => 'year',
                'status' => 'active',
                'pihak_pertama' => 'PT INTI (Persero)',
                'pihak_kedua' => 'PT. INTI KONTEN INDONESIA',
                'renewal_notes' => 'Per Tahun',
            ],
            // id 18: JADDASOLUTION  (id_tenant bisnis: 40211)
            [
                'id' => 18,
                'tenant_id' => 51,
                'contract_type' => 'sewa',
                'no_bak' => '2154/HK.03/030301/2025',
                'date_bak' => '2026-09-09',
                'file_bak' => null,
                'no_pks' => null,
                'date_pks' => null,
                'file_pks' => null,
                'start_date' => '2025-08-01',
                'end_date' => '2027-07-31',
                'total_rental_value' => 15120000,
                'security_deposit' => null,
                'sharing_type' => null,
                'company_share_pct' => null,
                'tenant_share_pct' => null,
                'payment_type' => 'upfront',
                'payment_start_date' => '2025-08-01',
                'payment_interval_value' => 1,
                'payment_interval_unit' => 'year',
                'status' => 'active',
                'pihak_pertama' => 'PT INTI (Persero)',
                'pihak_kedua' => 'JADDASOLUTION',
                'renewal_notes' => '100% diperhitungkan dengan nilai IPK',
            ],
            // id 19: Elfia Minisoccer  (id_tenant bisnis: 40228)
            [
                'id' => 19,
                'tenant_id' => 40,
                'contract_type' => 'ksu',
                'no_bak' => null,
                'date_bak' => null,
                'file_bak' => null,
                'no_pks' => '180/PL.01/040300/2023',
                'date_pks' => '2023-08-17',
                'file_pks' => null,
                'start_date' => '2023-08-17',
                'end_date' => '2027-08-16',
                'total_rental_value' => null,
                'security_deposit' => null,
                'sharing_type' => 'revenue_sharing',
                'company_share_pct' => 40,
                'tenant_share_pct' => 60,
                'payment_type' => 'interval',
                'payment_start_date' => '2023-08-17',
                'payment_interval_value' => 1,
                'payment_interval_unit' => 'month',
                'status' => 'active',
                'pihak_pertama' => 'PT INTI (Persero)',
                'pihak_kedua' => 'Elfia Minisoccer',
                'renewal_notes' => 'Per Bulan || KSU revenue_sharing; % porsi perusahaan diasumsikan 40.0% (verifikasi arah bagi hasil)',
            ],
            // id 21: PT EPID MENARA ASSETCO  (id_tenant bisnis: 40044)
            [
                'id' => 21,
                'tenant_id' => 16,
                'contract_type' => 'sewa',
                'no_bak' => '2525/PL.01/020804/2021',
                'date_bak' => '2021-10-27',
                'file_bak' => null,
                'no_pks' => '205/HK.03/020804/2022',
                'date_pks' => '2022-10-06',
                'file_pks' => null,
                'start_date' => '2023-06-05',
                'end_date' => '2027-10-27',
                'total_rental_value' => 115133200,
                'security_deposit' => null,
                'sharing_type' => null,
                'company_share_pct' => null,
                'tenant_share_pct' => null,
                'payment_type' => 'upfront',
                'payment_start_date' => '2023-06-05',
                'payment_interval_value' => 1,
                'payment_interval_unit' => 'year',
                'status' => 'active',
                'pihak_pertama' => 'PT INTI (Persero)',
                'pihak_kedua' => 'PT EPID MENARA ASSETCO',
                'renewal_notes' => '100% dibayar dimuka',
            ],
            // id 23: PT. WIDYA BHAKTI INTI (WBI) Gd D Poli  (id_tenant bisnis: 40060)
            [
                'id' => 23,
                'tenant_id' => 23,
                'contract_type' => 'sewa',
                'no_bak' => '386/HK.03/030302/2023',
                'date_bak' => '2023-02-18',
                'file_bak' => null,
                'no_pks' => '57/HK.03/030300/2023',
                'date_pks' => '2023-03-13',
                'file_pks' => null,
                'start_date' => '2023-01-01',
                'end_date' => '2027-12-31',
                'total_rental_value' => 787158000,
                'security_deposit' => null,
                'sharing_type' => null,
                'company_share_pct' => null,
                'tenant_share_pct' => null,
                'payment_type' => 'upfront',
                'payment_start_date' => '2023-01-01',
                'payment_interval_value' => 1,
                'payment_interval_unit' => 'year',
                'status' => 'active',
                'pihak_pertama' => 'PT INTI (Persero)',
                'pihak_kedua' => 'PT. WIDYA BHAKTI INTI (WBI) Gd D Poli',
                'renewal_notes' => '100% dibayar dimuka realisasi balancing',
            ],
            // id 24: Parkir Palasari  (id_tenant bisnis: 40051)
            [
                'id' => 24,
                'tenant_id' => 45,
                'contract_type' => 'ksu',
                'no_bak' => '54/HK.03/030300/2025',
                'date_bak' => '2025-03-24',
                'file_bak' => null,
                'no_pks' => '55/HK.03/030300/2025',
                'date_pks' => '2025-04-25',
                'file_pks' => null,
                'start_date' => '2025-04-01',
                'end_date' => '2028-03-31',
                'total_rental_value' => null,
                'security_deposit' => null,
                'sharing_type' => 'revenue_sharing',
                'company_share_pct' => 65,
                'tenant_share_pct' => 35,
                'payment_type' => 'interval',
                'payment_start_date' => '2025-04-01',
                'payment_interval_value' => 1,
                'payment_interval_unit' => 'month',
                'status' => 'active',
                'pihak_pertama' => 'PT INTI (Persero)',
                'pihak_kedua' => 'Parkir Palasari',
                'renewal_notes' => 'Per Bulan || KSU revenue_sharing; % porsi perusahaan diasumsikan 65.0% (verifikasi arah bagi hasil)',
            ],
            // id 25: Parkir Toha 77  (id_tenant bisnis: 40026)
            [
                'id' => 25,
                'tenant_id' => 44,
                'contract_type' => 'ksu',
                'no_bak' => '152/HK.03/030301/2025',
                'date_bak' => '2025-08-11',
                'file_bak' => null,
                'no_pks' => null,
                'date_pks' => null,
                'file_pks' => null,
                'start_date' => '2025-04-01',
                'end_date' => '2028-03-31',
                'total_rental_value' => null,
                'security_deposit' => null,
                'sharing_type' => 'revenue_sharing',
                'company_share_pct' => 60,
                'tenant_share_pct' => 40,
                'payment_type' => 'interval',
                'payment_start_date' => '2025-04-01',
                'payment_interval_value' => 1,
                'payment_interval_unit' => 'month',
                'status' => 'active',
                'pihak_pertama' => 'PT INTI (Persero)',
                'pihak_kedua' => 'Parkir Toha 77',
                'renewal_notes' => 'Per bulan || KSU revenue_sharing; % porsi perusahaan diasumsikan 60.0% (verifikasi arah bagi hasil)',
            ],
            // id 26: PT. BANK OCBC NISP,Tbk  (id_tenant bisnis: 40034)
            [
                'id' => 26,
                'tenant_id' => 28,
                'contract_type' => 'sewa',
                'no_bak' => null,
                'date_bak' => null,
                'file_bak' => null,
                'no_pks' => '2155/HK.03/030301/2025',
                'date_pks' => '2025-10-14',
                'file_pks' => null,
                'start_date' => '2025-12-31',
                'end_date' => '2028-12-30',
                'total_rental_value' => 151200000,
                'security_deposit' => null,
                'sharing_type' => null,
                'company_share_pct' => null,
                'tenant_share_pct' => null,
                'payment_type' => 'upfront',
                'payment_start_date' => '2025-12-31',
                'payment_interval_value' => 1,
                'payment_interval_unit' => 'year',
                'status' => 'active',
                'pihak_pertama' => 'PT INTI (Persero)',
                'pihak_kedua' => 'PT. BANK OCBC NISP,Tbk',
                'renewal_notes' => '100% dibayar dimuka',
            ],
            // id 27: PT Navitas Educational Service  (id_tenant bisnis: 40238)
            [
                'id' => 27,
                'tenant_id' => 4,
                'contract_type' => 'sewa',
                'no_bak' => null,
                'date_bak' => null,
                'file_bak' => null,
                'no_pks' => '37/HK.03/030302/2024',
                'date_pks' => '2024-03-25',
                'file_pks' => null,
                'start_date' => '2024-09-01',
                'end_date' => '2029-08-31',
                'total_rental_value' => 26028217200,
                'security_deposit' => null,
                'sharing_type' => null,
                'company_share_pct' => null,
                'tenant_share_pct' => null,
                'payment_type' => 'interval',
                'payment_start_date' => '2024-09-01',
                'payment_interval_value' => 3,
                'payment_interval_unit' => 'month',
                'status' => 'active',
                'pihak_pertama' => 'PT INTI (Persero)',
                'pihak_kedua' => 'PT Navitas Educational Service',
                'renewal_notes' => 'Per 3 bulan',
            ],
            // id 28: YAYASAN DIAN KENCANA INTI 2 Gd AD  (id_tenant bisnis: 40194)
            [
                'id' => 28,
                'tenant_id' => 22,
                'contract_type' => 'sewa',
                'no_bak' => '150/HK/03/030300/2024',
                'date_bak' => '2024-10-15',
                'file_bak' => null,
                'no_pks' => '152/HK.03/030302/2025',
                'date_pks' => '2025-10-15',
                'file_pks' => null,
                'start_date' => '2024-11-01',
                'end_date' => '2029-10-31',
                'total_rental_value' => 1000000000,
                'security_deposit' => null,
                'sharing_type' => null,
                'company_share_pct' => null,
                'tenant_share_pct' => null,
                'payment_type' => 'interval',
                'payment_start_date' => '2024-11-01',
                'payment_interval_value' => 1,
                'payment_interval_unit' => 'year',
                'status' => 'active',
                'pihak_pertama' => 'PT INTI (Persero)',
                'pihak_kedua' => 'YAYASAN DIAN KENCANA INTI 2 Gd AD',
                'renewal_notes' => 'Per tahun',
            ],
        ];

        foreach ($contracts as $row) {
            DB::table('contracts')->insert(array_merge($row, [
                'created_at' => $now,
                'updated_at' => $now,
            ]));
        }
    }
}
